### ISSUE TITLE
We cannot see the cursor when we are in the identation

### ISSUE THREAD

**Issue by Ganbin** [harai/indent-guide-improved#68]
If we move the cursor in an indented line, the cursor disappear, it make we to loose the knwoledge of where the cursor is.

I give you 2 picture. one with the cursor juste before the ident line and the one after with the 3 red arrow showing that we do not see anymore where is the cursor 

From the `OK` to the `Not OK` picture I have juste moved the cursor with the `left arrow key`

![OK](https://user-images.githubusercontent.com/1487962/28112167-526e7fc2-66f8-11e7-8649-40e63b8a5545.png)

![Not OK](https://user-images.githubusercontent.com/1487962/28112175-54f4c4cc-66f8-11e7-84dd-8eac38cbc3d7.png)

**Comment by AnimiVulpis** [comment]
I found a pretty easy workaround for this problem:

You need to set your own colors for the guides (at least `indent-guide-stack` and `indent-guide-active`, because those can _hide_ your cursor)
**and** use the `less` function `fadeout` (`fadein` and `fade` should work too I assume)

### Example (using currently active theme colors):

In your atom `styles.less` (access via `Stylesheet...` menu option):

```less
// Import styleguide colors
@import 'ui-variables';
// indent-guide-improved settings
.indent-guide-improved {
  background-color: @background-color-highlight;
  &.indent-guide-stack {
    background-color: fadeout(@text-color-info, 50%);
    &.indent-guide-active {
      background-color: fadeout(@background-color-success, 50%);
    }
  }
}
```

Hope that helps
